const menuItems = [
	// 'SHOP BY CATEGORY',
	'Prime Video',
	'Amazon Music',
	'Apps for Android',
	'Echo & Alexa',
	'Fire TV',
	'Fire Tablets',
	'Kindle E-readers & Books',
	'Audible Audiobooks',
	'Find a Gift',
	'Books',
	'Films, TV, Music & Games',
	'Electronics & Computers',
	'Home, Garden, Pets & DIY',
	'Toys, Children & Baby',
	'Clothes, Shoes & Watches',
	'Sports & Outdoors',
	'Food & Grocery',
	'Health & Beauty',
	'Car & Motorbike',
	'Business, Industry & Science',
	'Gift Cards & Top Up',
	'Handmade',
	'Amazon Launchpad',
	'Made in Italy',
	'Home Services',
	'Prime Wardrobe',
	'Amazon Storefronts',
	'Amazon Business',
	'Amazon Second Chance',
	'Full Shop Directory',
	// 'HELP & SETTINGS',
	// 'Your Account',
	// 'Customer Service',
	// 'Sign Out',
];

export default menuItems;
